#!/usr/bin/env bash
#configures redirection page.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo Hello World > replace
cp replace /var/www/html/index.nginx-debian.html
rm replace
sed -i "/server_name _/a \        rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
sudo service nginx restart
