#!/usr/bin/env bash
# "bad luck" in the 4th  "good luck" in the 8th ,
# and "Best school" in the rest.
counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo bad luck
	elif [ $counter -eq 8 ]
	then
		echo good luck
	else
		echo Best School
	fi
	((counter++))
done
