#!/usr/bin/env bash
# test if the holbertonschool file exists and if it is empty.
if [ -e holbertonschool ]
then
	echo "School file exists"
	if [ -s holbertonschool ]
	then
		echo "School file is not empty"
	else
		echo "School file is empty"
	fi
	if [ -f holbertonschool ]
	then
		echo "School is a regular file"
	fi
else
	echo "School file does not exist"
fi
